// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    AComment: typeof import('ant-design-vue/es')['Comment']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    APageHeader: typeof import('ant-design-vue/es')['PageHeader']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ChannelAddButton: typeof import('./src/components/ChannelAddButton.vue')['default']
    HeartFilled: typeof import('@ant-design/icons-vue')['HeartFilled']
    MessageOutlined: typeof import('@ant-design/icons-vue')['MessageOutlined']
  }
}

export { }
